version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: storke_central
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  jaeger:
    image: jaegertracing/all-in-one:1.47
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
      COLLECTOR_OTLP_ENABLED: true

  montecito:
    container_name: montecito
    depends_on:
      - db
      - rincon
      - jaeger
    build: ./montecito
    image: bk1031/sc_montecito
    ports:
      - "${MONTECITO_PORT}:${MONTECITO_PORT}"
    environment:
      ENV: $ENV
      SERVICE_NAME: "Montecito"
      PORT: $MONTECITO_PORT
      RINCON_PORT: $RINCON_PORT
      JAEGER_PORT: $JAEGER_PORT
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      DISCORD_TOKEN: $DISCORD_TOKEN
      DISCORD_GUILD: $DISCORD_GUILD
      DISCORD_CHANNEL: $MONTECITO_DISCORD_CHANNEL
      STATUS_EMAIL: $MONTECITO_STATUS_EMAIL
      FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
      FIREBASE_SERVICE_ACCOUNT: $FIREBASE_SERVICE_ACCOUNT

  rincon:
    container_name: rincon
    depends_on:
      - db
      - jaeger
    build: ./rincon
    image: bk1031/sc_rincon
    ports:
      - "${RINCON_PORT}:${RINCON_PORT}"
    environment:
      ENV: $ENV
      SERVICE_NAME: "Rincon"
      PORT: $RINCON_PORT
      JAEGER_PORT: $JAEGER_PORT
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      EMAIL_ADDRESS: $RINCON_EMAIL_ADDRESS
      EMAIL_PASSWORD: $RINCON_EMAIL_PASSWORD
      DISCORD_TOKEN: $DISCORD_TOKEN
      DISCORD_GUILD: $DISCORD_GUILD
      DISCORD_CHANNEL: $RINCON_DISCORD_CHANNEL
      STATUS_EMAIL: $RINCON_STATUS_EMAIL
      REGISTRY_UPDATE_CRON: $RINCON_REGISTRY_UPDATE_CRON

  lacumbre:
    container_name: lacumbre
    depends_on:
      - db
      - rincon
    build: ./lacumbre
    image: bk1031/sc_lacumbre
    ports:
      - "${LACUMBRE_PORT}:${LACUMBRE_PORT}"
    environment:
      ENV: $ENV
      SERVICE_NAME: "Lacumbre"
      PORT: $LACUMBRE_PORT
      RINCON_PORT: $RINCON_PORT
      JAEGER_PORT: $JAEGER_PORT
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      DISCORD_TOKEN: $DISCORD_TOKEN
      DISCORD_GUILD: $DISCORD_GUILD
      DISCORD_CHANNEL: $LACUMBRE_DISCORD_CHANNEL
      STATUS_EMAIL: $LACUMBRE_STATUS_EMAIL
      FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
      FIREBASE_SERVICE_ACCOUNT: $FIREBASE_SERVICE_ACCOUNT

  gaviota:
    container_name: gaviota
    depends_on:
      - db
      - rincon
    build: ./gaviota
    image: bk1031/sc_gaviota
    ports:
      - "${GAVIOTA_PORT}:${GAVIOTA_PORT}"
    environment:
      ENV: $ENV
      SERVICE_NAME: "Gaviota"
      PORT: $GAVIOTA_PORT
      RINCON_PORT: $RINCON_PORT
      JAEGER_PORT: $JAEGER_PORT
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      DISCORD_TOKEN: $DISCORD_TOKEN
      DISCORD_GUILD: $DISCORD_GUILD
      DISCORD_CHANNEL: $GAVIOTA_DISCORD_CHANNEL
      STATUS_EMAIL: $GAVIOTA_STATUS_EMAIL
      FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
      FIREBASE_SERVICE_ACCOUNT: $FIREBASE_SERVICE_ACCOUNT
      ARTICLE_UPDATE_CRON: $GAVIOTA_ARTICLE_UPDATE_CRON

  tepusquet:
    container_name: tepusquet
    depends_on:
      - db
      - rincon
    build: ./tepusquet
    image: bk1031/sc_tepusquet
    ports:
      - "${TEPUSQUET_PORT}:${TEPUSQUET_PORT}"
    deploy:
      mode: global
      resources:
        limits:
          memory: 2gb
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      ENV: $ENV
      SERVICE_NAME: "Tepusquet"
      PORT: $TEPUSQUET_PORT
      RINCON_PORT: $RINCON_PORT
      JAEGER_PORT: $JAEGER_PORT
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      DISCORD_TOKEN: $DISCORD_TOKEN
      DISCORD_GUILD: $DISCORD_GUILD
      DISCORD_CHANNEL: $TEPUSQUET_DISCORD_CHANNEL
      STATUS_EMAIL: $TEPUSQUET_STATUS_EMAIL
      FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
      FIREBASE_SERVICE_ACCOUNT: $FIREBASE_SERVICE_ACCOUNT
      CRED_ENCRYPTION_KEY: $TEPUSQUET_CRED_ENCRYPTION_KEY
      UP_NEXT_UPDATE_CRON: $TEPUSQUET_UP_NEXT_UPDATE_CRON
      NOTIFICATION_CRON: $TEPUSQUET_NOTIFICATION_CRON
      CURRENT_QUARTER: $TEPUSQUET_CURRENT_QUARTER
      CURRENT_PASSTIME_QUARTER: $TEPUSQUET_CURRENT_PASSTIME_QUARTER

  arguello:
    container_name: arguello
    depends_on:
      - db
      - rincon
    build: ./arguello
    image: bk1031/sc_arguello
    ports:
      - "${ARGUELLO_PORT}:${ARGUELLO_PORT}"
    environment:
      ENV: $ENV
      SERVICE_NAME: "Arguello"
      PORT: $ARGUELLO_PORT
      RINCON_PORT: $RINCON_PORT
      JAEGER_PORT: $JAEGER_PORT
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      DISCORD_TOKEN: $DISCORD_TOKEN
      DISCORD_GUILD: $DISCORD_GUILD
      DISCORD_CHANNEL: $ARGUELLO_DISCORD_CHANNEL
      STATUS_EMAIL: $ARGUELLO_STATUS_EMAIL
      FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
      FIREBASE_SERVICE_ACCOUNT: $FIREBASE_SERVICE_ACCOUNT

  miranda:
    container_name: miranda
    depends_on:
      - db
      - rincon
    build: ./miranda
    image: bk1031/sc_miranda
    ports:
      - "${MIRANDA_PORT}:${MIRANDA_PORT}"
    environment:
      ENV: $ENV
      SERVICE_NAME: "Miranda"
      PORT: $MIRANDA_PORT
      RINCON_PORT: $RINCON_PORT
      JAEGER_PORT: $JAEGER_PORT
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      DISCORD_TOKEN: $DISCORD_TOKEN
      DISCORD_GUILD: $DISCORD_GUILD
      DISCORD_CHANNEL: $MIRANDA_DISCORD_CHANNEL
      STATUS_EMAIL: $MIRANDA_STATUS_EMAIL
      FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
      FIREBASE_SERVICE_ACCOUNT: $FIREBASE_SERVICE_ACCOUNT
      ONESIGNAL_APP_ID: $MIRANDA_ONESIGNAL_APP_ID
      ONESIGNAL_API_KEY: $MIRANDA_ONESIGNAL_API_KEY

  jalama:
    container_name: jalama
    depends_on:
      - db
      - rincon
    build: ./jalama
    image: bk1031/sc_jalama
    ports:
      - "${JALAMA_PORT}:${JALAMA_PORT}"
    environment:
      ENV: $ENV
      SERVICE_NAME: "Jalama"
      PORT: $JALAMA_PORT
      RINCON_PORT: $RINCON_PORT
      JAEGER_PORT: $JAEGER_PORT
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      DISCORD_TOKEN: $DISCORD_TOKEN
      DISCORD_GUILD: $DISCORD_GUILD
      DISCORD_CHANNEL: $JALAMA_DISCORD_CHANNEL
      STATUS_EMAIL: $JALAMA_STATUS_EMAIL
      FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
      FIREBASE_SERVICE_ACCOUNT: $FIREBASE_SERVICE_ACCOUNT
      MEAL_UPDATE_DAYS: $JALAMA_MEAL_UPDATE_DAYS
      MEAL_UPDATE_CRON: $JALAMA_MEAL_UPDATE_CRON
      UCSB_API_KEY: $UCSB_API_KEY

volumes:
  pgdata: